### ISSUE TITLE
zj  你好

### ISSUE THREAD

**Issue by liu5855019** [Abnerzj/ZJPickerView#1]
#### 但是使用你的demo过程中,出现了小小的bug

![c71d55fcb04efc15e0cd2b0c925abe11](https://user-images.githubusercontent.com/16952427/38465599-73539948-3b50-11e8-8ecd-9fa6ab494736.png)

如图,   快速滚动选择列的时候,同时点击确定按钮     会出现如图情况

**Comment by Abnerzj** [comment]
你好，感谢你提出的问题。本库核心还是基于UIPickerView实现，查看了苹果UIPickerView相关的API，发现没有相关的代理方法监听每一列正在滚动，即无法监听到用户滚动时松手之前当前滚动到哪一行，所以也无法取到相关内容给中间的标题赋值。苹果API只提供了当用户滚动停止松手后才做相关的代理回传，请参考：- (nullable NSAttributedString *)pickerView:(UIPickerView *)pickerView attributedTitleForRow:(NSInteger)row forComponent:(NSInteger)component 方法。
