### ISSUE TITLE
设置滑动到指定行出错

### ISSUE THREAD

**Issue by popor** [Abnerzj/ZJPickerView#4]
参数
NSArray *  dataList = @[@"500", @"1500", @"2500", @"3500"];
ZJPickerViewPropertyTipLabelTextKey:@"1500"
ZJPickerViewPropertyIsScrollToSelectedRowKey:@YES

只会滑动第一行,应该是下面函数判断有误.

if (![title isEqualToString:@""]) {
    NSRange range = [selectedContent rangeOfString:title];
    if (range.location != NSNotFound) {
        [tempSelectedRowArray addObject:@(idx)];
        [weakself.pickerView reloadComponent:i];
        [weakself.pickerView selectRow:idx inComponent:i animated:NO];
        [weakself.pickerView reloadComponent:i];
        *stop = YES;
    }
}

**Comment by Abnerzj** [comment]
你好，谢谢你提出的问题。测试发现，只有一列数据 且 当两个数据内容都相似时，会出现这个问题。1.0.3版本已经解决这个问题，请稍后直接更新一下pod。

**Comment by Abnerzj** [comment]
1.0.3版本已经发布，直接更新一下pod就行。

**Comment by popor** [comment]
ok了,很完美!
