### ISSUE TITLE
设置滑动到指定行出错

### ISSUE THREAD

**Issue by popor** [Abnerzj/ZJPickerView#5]
参数
NSArray * dataList = @[@"500", @"1000", @"5000", @"50000"];
ZJPickerViewPropertyTipLabelTextKey:@"50000"
ZJPickerViewPropertyIsScrollToSelectedRowKey:@YES

只会滑动第一行.

**Comment by popor** [comment]
有时间处理下吗？

**Comment by Abnerzj** [comment]
你好，最新版本1.0.3已经解决了这个问题。

**Comment by Abnerzj** [comment]
你好，感谢你提出的问题，刚刚检查了确实有这个问题，新版本1.0.4已经解决。

**Comment by popor** [comment]
确实ok了
