### ISSUE TITLE
通过propertyDict 给toolbar的tiplabel赋默认值，不能显示 被updater覆盖

### ISSUE THREAD

**Issue by OPTJoker** [Abnerzj/ZJPickerView#6]
519行的【 self.tipLabel.hidden = !self.isShowSelectContent 】这句代码会影响toolBar tipText的默认值。
tipText先赋值，因为没有选中任何行，所以控件被hidden掉了，望修改~

**Comment by Abnerzj** [comment]
你好，感谢你提出的问题。在给propertyDict设置值时，把ZJPickerViewPropertyIsShowSelectContentKey设置为YES，就可以保证tiplabel不被隐藏，同时在滚动的到某一行时自动更新tiplabel的值。
PS：目前v1.0.4版本未做tiplabel只显示一个值功能。

**Comment by Abnerzj** [comment]
v1.0.5版本已经添加tiplabel只显示一个值的功能
