### ISSUE TITLE
设置已选数据出错

### ISSUE THREAD

**Issue by monkiyang** [Abnerzj/ZJPickerView#8]
使用版本 1.0.1
比如已选19.2，显示9.2
调试代码发现把
```
NSRange range = [componetSelectedContent rangeOfString:title];
if (range.location != NSNotFound) {
    [tempSelectedRowArray addObject:@(idx)];
    [weakself.pickerView reloadComponent:i];
    [weakself.pickerView selectRow:idx inComponent:i animated:NO];
    [weakself.pickerView reloadComponent:i];
    *stop = YES;
}
```
改为
```
if ([selectedContent isEqualToString:title]) {
    [tempSelectedRowArray addObject:@(idx)];
    [weakself.pickerView reloadComponent:i];
    [weakself.pickerView selectRow:idx inComponent:i animated:NO];
    [weakself.pickerView reloadComponent:i];
    *stop = YES;
}
```
可行

**Comment by Abnerzj** [comment]
谢谢，1.0.1版本确实存在此问题，请更新最新版本1.0.5即可解决此问题。

**Comment by monkiyang** [comment]
更新到1.0.5版本
```
// discussion: scroll to select row error when solving content similar, only appear when there is only one component.
// reference: https://github.com/Abnerzj/ZJPickerView/issues/4
//            https://github.com/Abnerzj/ZJPickerView/issues/5
NSRange range = [selectedContent rangeOfString:title];
if ((self.component == 1 && i == 0) ? ([selectedContent isEqualToString:title]) : (range.location != NSNotFound)) {
    [tempSelectedRowArray addObject:@(idx)];
    [weakself.pickerView reloadComponent:i];
    [weakself.pickerView selectRow:idx inComponent:i animated:NO];
    [weakself.pickerView reloadComponent:i];
    *stop = YES;
}
```
断点打印：self.component = 2, i = 1, selectedContent = @"15,.0", title = @"5"
问题仍然存在，还是把判断条件改为了`[selectedContent isEqualToString:title]`

**Comment by Abnerzj** [comment]
能否提供完整的测试数据

**Comment by Winlet** [comment]
通过NSRange对于日期选择器来说是不可行的.
因为纯数字,年份里面很容易出现月份或者天数的数字的.

看了下`ZJPickerViewPropertyTipLabelTextKey`对于多列数据没有具体的传递规则.
我参考你解数据的方式用','区别了,做了很小的改动.
因为不知道其他人的问题具体是什么,所以发给你看下是否有潜藏问题
请你可以综合一下,给我个答复.
` NSString *selectedContent = self.propertyDict[ZJPickerViewPropertyTipLabelTextKey];
    NSArray *selectedArray = [selectedContent componentsSeparatedByString:@","];
    
    if (selectedContent.length && ![selectedContent isEqualToString:@""]) {
        __weak typeof(self) weakself = self;
        NSMutableArray *tempSelectedRowArray = [NSMutableArray arrayWithCapacity:self.component];
        for (NSUInteger i = 0; i < self.component; i++) {
            NSArray *componentArray = [self getDataWithComponent:i];
            NSString *componentString = [selectedArray objectAtIndex:i];
            if (componentArray.count) {
                [componentArray enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL * _Nonnull stop) {
                    NSString *title = @"";
                    if ([obj isKindOfClass:[NSString class]]) {
                        title = obj;
                    } else if ([obj isKindOfClass:[NSNumber class]]) {
                        title = [NSString stringWithFormat:@"%@", obj];
                    }
                    if (![title isEqualToString:@""]) {
                        // discussion: scroll to select row error when solving content similar, only appear when there is only one component.
                        // reference: https://github.com/Abnerzj/ZJPickerView/issues/4
                        //            https://github.com/Abnerzj/ZJPickerView/issues/5
                        
                        if ([componentString isEqualToString:title]) {
                            [tempSelectedRowArray addObject:@(idx)];
                            [weakself.pickerView reloadComponent:i];
                            [weakself.pickerView selectRow:idx inComponent:i animated:NO];
                            [weakself.pickerView reloadComponent:i];
                            *stop = YES;
                        }
                    }`

**Comment by Abnerzj** [comment]
感谢你们的指出，之前滚动到每一列选中的内容之处时，是直接通过整个选中的内容进行字符串匹配，这种方式存在一个弊端，就是如果有多列都存在同样的数据时，就会得到滚动的位置不准确。

要改变这个问题，只能通过用户自己分割选中的内容，传递选择的内容集合过来进行匹配。

我的想法也跟你一样，目前已经发布了v1.0.6版本，解决此问题。如果还有什么问题，欢迎你给我留言。

PS：多列数据时实现滚动到每一列选中的行实现步骤：
1，将每一列选中的内容用英文逗号连接起来，比如：上海,虹口区。
2，设置属性`ZJPickerViewPropertyIsDividedSelectContentKey`为@YES。

**Comment by Abnerzj** [comment]
> 更新到1.0.5版本
> 
> ```
> // discussion: scroll to select row error when solving content similar, only appear when there is only one component.
> // reference: https://github.com/Abnerzj/ZJPickerView/issues/4
> //            https://github.com/Abnerzj/ZJPickerView/issues/5
> NSRange range = [selectedContent rangeOfString:title];
> if ((self.component == 1 && i == 0) ? ([selectedContent isEqualToString:title]) : (range.location != NSNotFound)) {
>     [tempSelectedRowArray addObject:@(idx)];
>     [weakself.pickerView reloadComponent:i];
>     [weakself.pickerView selectRow:idx inComponent:i animated:NO];
>     [weakself.pickerView reloadComponent:i];
>     *stop = YES;
> }
> ```
> 
> 断点打印：self.component = 2, i = 1, selectedContent = @"15,.0", title = @"5"
> 问题仍然存在，还是把判断条件改为了`[selectedContent isEqualToString:title]`

能否提供完整的测试数据

**Comment by Abnerzj** [comment]
> 使用版本 1.0.1
> 比如已选19.2，显示9.2
> 调试代码发现把
> 
> ```
> NSRange range = [componetSelectedContent rangeOfString:title];
> if (range.location != NSNotFound) {
>     [tempSelectedRowArray addObject:@(idx)];
>     [weakself.pickerView reloadComponent:i];
>     [weakself.pickerView selectRow:idx inComponent:i animated:NO];
>     [weakself.pickerView reloadComponent:i];
>     *stop = YES;
> }
> ```
> 
> 改为
> 
> ```
> if ([selectedContent isEqualToString:title]) {
>     [tempSelectedRowArray addObject:@(idx)];
>     [weakself.pickerView reloadComponent:i];
>     [weakself.pickerView selectRow:idx inComponent:i animated:NO];
>     [weakself.pickerView reloadComponent:i];
>     *stop = YES;
> }
> ```
> 
> 可行


> 使用版本 1.0.1
> 比如已选19.2，显示9.2
> 调试代码发现把
> 
> ```
> NSRange range = [componetSelectedContent rangeOfString:title];
> if (range.location != NSNotFound) {
>     [tempSelectedRowArray addObject:@(idx)];
>     [weakself.pickerView reloadComponent:i];
>     [weakself.pickerView selectRow:idx inComponent:i animated:NO];
>     [weakself.pickerView reloadComponent:i];
>     *stop = YES;
> }
> ```
> 
> 改为
> 
> ```
> if ([selectedContent isEqualToString:title]) {
>     [tempSelectedRowArray addObject:@(idx)];
>     [weakself.pickerView reloadComponent:i];
>     [weakself.pickerView selectRow:idx inComponent:i animated:NO];
>     [weakself.pickerView reloadComponent:i];
>     *stop = YES;
> }
> ```
> 
> 可行

请更新v1.0.6版本看下是否还有问题。

**Comment by Abnerzj** [comment]
> 更新到1.0.5版本
> 
> ```
> // discussion: scroll to select row error when solving content similar, only appear when there is only one component.
> // reference: https://github.com/Abnerzj/ZJPickerView/issues/4
> //            https://github.com/Abnerzj/ZJPickerView/issues/5
> NSRange range = [selectedContent rangeOfString:title];
> if ((self.component == 1 && i == 0) ? ([selectedContent isEqualToString:title]) : (range.location != NSNotFound)) {
>     [tempSelectedRowArray addObject:@(idx)];
>     [weakself.pickerView reloadComponent:i];
>     [weakself.pickerView selectRow:idx inComponent:i animated:NO];
>     [weakself.pickerView reloadComponent:i];
>     *stop = YES;
> }
> ```
> 
> 断点打印：self.component = 2, i = 1, selectedContent = @"15,.0", title = @"5"
> 问题仍然存在，还是把判断条件改为了`[selectedContent isEqualToString:title]`

请更新v1.0.6版本看下是否还有问题。

**Comment by monkiyang** [comment]
更新到1.0.6版本，是解决了，以下是我对此问题的看法：
多行选择器，旧版本对已选内容是要求每列选中数据用 "," 组合起来，这个我有做了处理，新版本加入属性`ZJPickerViewPropertyIsDividedSelectContentKey`控制，有无必要？按我理解的，你内部逻辑是先做 “,” 分割，然后拿分割出来的数据，去每列的数据集里面做匹配，而匹配是用的`rangeOfString`方法，这是模糊匹配的，当出现已选是15，数据集中到5时，匹配出来的range.location是不等于NSNotFound的，这样ZJPickerView就选到了5了，所以我才改用了[selectedContent isEqualToString:title]方法做精准匹配。
出现了新的问题，中间标题带了 "," 号，比如 "15,.0" ，旧版本有用 "" 替换掉 "," 。

**Comment by Abnerzj** [comment]
> 更新到1.0.6版本，是解决了，以下是我对此问题的看法：
> 多行选择器，旧版本对已选内容是要求每列选中数据用 "," 组合起来，这个我有做了处理，新版本加入属性`ZJPickerViewPropertyIsDividedSelectContentKey`控制，有无必要？按我理解的，你内部逻辑是先做 “,” 分割，然后拿分割出来的数据，去每列的数据集里面做匹配，而匹配是用的`rangeOfString`方法，这是模糊匹配的，当出现已选是15，数据集中到5时，匹配出来的range.location是不等于NSNotFound的，这样ZJPickerView就选到了5了，所以我才改用了[selectedContent isEqualToString:title]方法做精准匹配。
> 出现了新的问题，中间标题带了 "," 号，比如 "15,.0" ，旧版本有用 "" 替换掉 "," 。

你好，v1.0.6之前的版本，处理滚动到每一列选中的内容之处时，是直接通过整个选中的内容进行字符串匹配，这种方式存在一个弊端，就是如果有多列都存在同样的数据时，就会得到滚动的位置不准确。

要改变这个问题，只能通过用户自己分割选中的内容，传递选择的内容集合过来进行匹配。

v1.0.6+版本开始，提供`ZJPickerViewPropertyIsDividedSelectContentKey`给开发者设置，告诉`ZJPickerView`选中的内容已经用英文逗号连接起来，这样`ZJPickerView`才知道需要去做分割处理，如果不设置还是会走之前的字符串模糊匹配，也是为了不影响集成了旧版本App的使用。

另外，`selectedContent`有可能是多列选中的内容拼接起来的字符串，不能用`[selectedContent isEqualToString:title]`这种方式去匹配。如果做了下面两个步骤，满足了条件，`ZJPickerView`会根据选中内容集合做精准匹配：`[selectContentList[i] isEqualToString:title]`。

PS：多列数据时实现滚动到每一列选中的行实现步骤：
1，将每一列选中的内容用英文逗号连接起来，比如：`上海,虹口区`。
2，设置属性`ZJPickerViewPropertyIsDividedSelectContentKey`为`@YES`。
